export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

export const BADGE_LIST_REQUEST = "BADGE_LIST_REQUEST";
export const BADGE_LIST_SUCCESS = "BADGE_LIST_SUCCESS";
export const BADGE_LIST_FAIL = "BADGE_LIST_FAIL";

export const BADGE_CREATE_REQUEST = "BADGE_CREATE_REQUEST";
export const BADGE_CREATE_SUCCESS = "BADGE_CREATE_SUCCESS";
export const BADGE_CREATE_FAIL = "BADGE_CREATE_FAIL";
export const BADGE_CREATE_RESET = "BADGE_CREATE_RESET";

export const BADGE_ADD_REQUEST = "BADGE_ADD_REQUEST";
export const BADGE_ADD_SUCCESS = "BADGE_ADD_SUCCESS";
export const BADGE_ADD_FAIL = "BADGE_ADD_FAIL";

export const SKILL_LIST_REQUEST = "SKILL_LIST_REQUEST";
export const SKILL_LIST_SUCCESS = "SKILL_LIST_SUCCESS";
export const SKILL_LIST_FAIL = "SKILL_LIST_FAIL";

export const SKILL_CREATE_REQUEST = "SKILL_CREATE_REQUEST";
export const SKILL_CREATE_SUCCESS = "SKILL_CREATE_SUCCESS";
export const SKILL_CREATE_FAIL = "SKILL_CREATE_FAIL";
export const SKILL_CREATE_RESET = "SKILL_CREATE_RESET";

export const SKILL_UPDATE_REQUEST = "SKILL_UPDATE_REQUEST";
export const SKILL_UPDATE_SUCCESS = "SKILL_UPDATE_SUCCESS";
export const SKILL_UPDATE_FAIL = "SKILL_UPDATE_FAIL";
