export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

export const USER_ADD_ACHIEVEMENT_REQUEST = "USER_ADD_ACHIEVEMENT_REQUEST";
export const USER_ADD_ACHIEVEMENT_SUCCESS = "USER_ADD_ACHIEVEMENT_SUCCESS";
export const USER_ADD_ACHIEVEMENT_FAIL = "USER_ADD_ACHIEVEMENT_FAIL";
export const USER_ADD_ACHIEVEMENT_RESET = "USER_ADD_ACHIEVEMENT_RESET";

export const BADGE_LIST_REQUEST = "BADGE_LIST_REQUEST";
export const BADGE_LIST_SUCCESS = "BADGE_LIST_SUCCESS";
export const BADGE_LIST_FAIL = "BADGE_LIST_FAIL";

export const BADGE_CREATE_REQUEST = "BADGE_CREATE_REQUEST";
export const BADGE_CREATE_SUCCESS = "BADGE_CREATE_SUCCESS";
export const BADGE_CREATE_FAIL = "BADGE_CREATE_FAIL";
export const BADGE_CREATE_RESET = "BADGE_CREATE_RESET";

export const BADGE_ADD_REQUEST = "BADGE_ADD_REQUEST";
export const BADGE_ADD_SUCCESS = "BADGE_ADD_SUCCESS";
export const BADGE_ADD_FAIL = "BADGE_ADD_FAIL";

export const SKILL_LIST_REQUEST = "SKILL_LIST_REQUEST";
export const SKILL_LIST_SUCCESS = "SKILL_LIST_SUCCESS";
export const SKILL_LIST_FAIL = "SKILL_LIST_FAIL";

export const SKILL_CREATE_REQUEST = "SKILL_CREATE_REQUEST";
export const SKILL_CREATE_SUCCESS = "SKILL_CREATE_SUCCESS";
export const SKILL_CREATE_FAIL = "SKILL_CREATE_FAIL";
export const SKILL_CREATE_RESET = "SKILL_CREATE_RESET";

export const USER_SKILL_UPDATE_REQUEST = "USER_SKILL_UPDATE_REQUEST";
export const USER_SKILL_UPDATE_SUCCESS = "USER_SKILL_UPDATE_SUCCESS";
export const USER_SKILL_UPDATE_FAIL = "USER_SKILL_UPDATE_FAIL";
export const USER_SKILL_UPDATE_RESET = "USER_SKILL_UPDATE_RESET";

export const ADD_BADGE_REQUEST = "ADD_BADGE_REQUEST";
export const ADD_BADGE_SUCCESS = "ADD_BADGE_SUCCESS";
export const ADD_BADGE_FAIL = "ADD_BADGE_FAIL";
export const ADD_BADGE_RESET = "ADD_BADGE_RESET";

export const HDATE_CREATE_REQUEST = "HDATE_CREATE_REQUEST";
export const HDATE_CREATE_SUCCESS = "HDATE_CREATE_SUCCESS";
export const HDATE_CREATE_FAIL = "HDATE_CREATE_FAIL";
export const HDATE_CREATE_RESET = "HDATE_CREATE_FAIL";

export const HDATE_GET_REQUEST = "HDATE_GET_REQUEST";
export const HDATE_GET_SUCCESS = "HDATE_GET_SUCCESS";
export const HDATE_GET_FAIL = "HDATE_GET_FAIL";

export const HDATE_DELETE_REQUEST = "HDATE_DELETE_REQUEST";
export const HDATE_DELETE_SUCCESS = "HDATE_DELETE_SUCCESS";
export const HDATE_DELETE_FAIL = "HDATE_DELETE_FAIL";

export const TITLE_CREATE_REQUEST = "TITLE_CREATE_REQUEST";
export const TITLE_CREATE_SUCCESS = "TITLE_CREATE_SUCCESS";
export const TITLE_CREATE_FAIL = "TITLE_CREATE_FAIL";
export const TITLE_CREATE_RESET = "TITLE_CREATE_RESET";

export const SUBTITLE_CREATE_REQUEST = "SUBTITLE_CREATE_REQUEST";
export const SUBTITLE_CREATE_SUCCESS = "SUBTITLE_CREATE_SUCCESS";
export const SUBTITLE_CREATE_FAIL = "SUBTITLE_CREATE_FAIL";
export const SUBTITLE_CREATE_RESET = "SUBTITLE_CREATE_RESET";

export const ACHIEVEMENTS_GET_REQUEST = "ACHIEVEMENTS_GET_REQUEST";
export const ACHIEVEMENTS_GET_SUCCESS = "ACHIEVEMENTS_GET_SUCCESS";
export const ACHIEVEMENTS_GET_FAIL = "ACHIEVEMENTS_GET_FAIL";
