export const ALL_USERS_SKILLS_REQUEST = "ALL_USERS_SKILLS_REQUEST";
export const ALL_USERS_SKILLS_SUCCESS = "ALL_USERS_SKILLS_SUCCESS";
export const ALL_USERS_SKILLS_FAIL = "ALL_USERS_SKILLS_FAIL";

export const COMPANY_REGISTER_REQUEST = "COMPANY_REGISTER_REQUEST";
export const COMPANY_REGISTER_SUCCESS = "COMPANY_REGISTER_SUCCESS";
export const COMPANY_REGISTER_FAIL = "COMPANY_REGISTER_FAIL";
