export const ALL_USERS_SKILLS_REQUEST = "ALL_USERS_SKILLS_REQUEST";
export const ALL_USERS_SKILLS_SUCCESS = "ALL_USERS_SKILLS_SUCCESS";
export const ALL_USERS_SKILLS_FAIL = "ALL_USERS_SKILLS_FAIL";

export const COMPANY_REGISTER_REQUEST = "COMPANY_REGISTER_REQUEST";
export const COMPANY_REGISTER_SUCCESS = "COMPANY_REGISTER_SUCCESS";
export const COMPANY_REGISTER_FAIL = "COMPANY_REGISTER_FAIL";

export const COMPANY_LOGIN_REQUEST = "COMPANY_LOGIN_REQUEST";
export const COMPANY_LOGIN_SUCCESS = "COMPANY_LOGIN_SUCCESS";
export const COMPANY_LOGIN_FAIL = "COMPANY_LOGIN_FAIL";
export const COMPANY_LOGOUT = "COMPANY_LOGOUT";

export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAIL = "VERIFICATION_FAIL";
